var PlayerConstants = {
  CURRENT_TRACK_RECEIVED: "CURRENT_TRACK_RECEIVED",
  TRACKS_RECEIVED: "TRACKS_RECEIVED",
  PLAYED: "PLAYED",
  PAUSED: "PAUSED",
  NEXT: "NEXT",
  PREV: "PREV",
  RESET: "RESET",
  PROGRESS: "PROGRESS",
  WAVE_RECEIVED: "WAVE_RECEIVED",
  WAVE_REMOUNTED: "WAVE_REMOUNTED",
  WAVE_UNMOUNTED: "WAVE_UNMOUNTED"
};

module.exports = PlayerConstants;
