var PlayerConstants = {
  PLAYED: "PLAYED",
  PAUSED: "PAUSED",
  NEXT: "NEXT",
  PREV: "PREV",
  RESET: "RESET",
  WAVE_RECEIVED: "WAVE_RECEIVED",
  WAVE_REMOUNTED: "WAVE_REMOUNTED",
  WAVE_UNMOUNTED: "WAVE_UNMOUNTED"
};

module.exports = PlayerConstants;
